[2024-06-24T04:52:10.687+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snowflake_connector3.snowfalke_task1 manual__2024-06-24T04:52:08.351494+00:00 [queued]>
[2024-06-24T04:52:10.698+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snowflake_connector3.snowfalke_task1 manual__2024-06-24T04:52:08.351494+00:00 [queued]>
[2024-06-24T04:52:10.699+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-06-24T04:52:10.716+0000] {taskinstance.py:1382} INFO - Executing <Task(SnowflakeOperator): snowfalke_task1> on 2024-06-24 04:52:08.351494+00:00
[2024-06-24T04:52:10.724+0000] {standard_task_runner.py:57} INFO - Started process 2583 to run task
[2024-06-24T04:52:10.728+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'snowflake_connector3', 'snowfalke_task1', 'manual__2024-06-24T04:52:08.351494+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/staging/rbroker/dag.py', '--cfg-path', '/tmp/tmpjmhh0g_l']
[2024-06-24T04:52:10.733+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask snowfalke_task1
[2024-06-24T04:52:10.792+0000] {task_command.py:416} INFO - Running <TaskInstance: snowflake_connector3.snowfalke_task1 manual__2024-06-24T04:52:08.351494+00:00 [running]> on host b00a3d1afa8e
[2024-06-24T04:52:10.887+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='snowflake_connector3' AIRFLOW_CTX_TASK_ID='snowfalke_task1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T04:52:08.351494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T04:52:08.351494+00:00'
[2024-06-24T04:52:10.888+0000] {sql.py:274} INFO - Executing: ['select 1;', 'show tables in database abcd_db;']
[2024-06-24T04:52:10.901+0000] {base.py:73} INFO - Using connection ID 'my_snowflake_conn' for task execution.
[2024-06-24T04:52:10.913+0000] {base.py:73} INFO - Using connection ID 'my_snowflake_conn' for task execution.
[2024-06-24T04:52:10.914+0000] {connection.py:334} INFO - Snowflake Connector for Python Version: 3.3.1, Python Version: 3.8.18, Platform: Linux-6.3.13-linuxkit-x86_64-with-glibc2.2.5
[2024-06-24T04:52:10.915+0000] {connection.py:1103} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-24T04:52:10.915+0000] {connection.py:1113} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-24T04:52:10.916+0000] {connection.py:1121} INFO - Setting use_openssl_only mode to False
[2024-06-24T04:52:11.030+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-24T04:52:11.391+0000] {cursor.py:833} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-06-24T04:52:11.471+0000] {cursor.py:846} INFO - query execution done
[2024-06-24T04:52:11.474+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2024-06-24T04:52:11.475+0000] {sql.py:418} INFO - Running statement: select 1;, parameters: None
[2024-06-24T04:52:11.475+0000] {cursor.py:833} INFO - query: [select 1;]
[2024-06-24T04:52:11.532+0000] {cursor.py:846} INFO - query execution done
[2024-06-24T04:52:11.533+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2024-06-24T04:52:11.534+0000] {sql.py:427} INFO - Rows affected: 1
[2024-06-24T04:52:11.543+0000] {snowflake.py:400} INFO - Rows affected: 1
[2024-06-24T04:52:11.544+0000] {snowflake.py:401} INFO - Snowflake query id: 01b53764-3201-46f7-0005-573a00031152
[2024-06-24T04:52:11.544+0000] {sql.py:418} INFO - Running statement: show tables in database abcd_db;, parameters: None
[2024-06-24T04:52:11.545+0000] {cursor.py:833} INFO - query: [show tables in database abcd_db;]
[2024-06-24T04:52:11.652+0000] {cursor.py:846} INFO - query execution done
[2024-06-24T04:52:11.663+0000] {connection.py:677} INFO - closed
[2024-06-24T04:52:11.685+0000] {connection.py:683} INFO - No async queries seem to be running, deleting session
[2024-06-24T04:52:11.711+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 937, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002043 (02000): 01b53764-3201-46f6-0005-573a0003216a: SQL compilation error:
Object does not exist, or operation cannot be performed.
[2024-06-24T04:52:11.722+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=snowflake_connector3, task_id=snowfalke_task1, execution_date=20240624T045208, start_date=20240624T045210, end_date=20240624T045211
[2024-06-24T04:52:11.738+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task snowfalke_task1 (002043 (02000): 01b53764-3201-46f6-0005-573a0003216a: SQL compilation error:
Object does not exist, or operation cannot be performed.; 2583)
[2024-06-24T04:52:11.790+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-24T04:52:11.811+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
